# Generated by Django 2.2.3 on 2019-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=24)),
                ('last_name', models.TextField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
